- name: ZEIT Now Deployment
  uses: amondnet/now-deployment@v2.0.3
  with:
    # zeit.co token
    zeit-token: 
    # 
    now-args: # optional, default is 
    # if you want to comment on pr and commit, set true, default: true
    github-comment: # optional, default is true
    # if you want to comment on pr and commit, set token
    github-token: # optional
    # if you want to create github deployment, set true, default: false
    github-deployment: # optional, default is false
    # the working directory
    working-directory: # optional
    # Now CLI 17+, ❗️  The `name` property in now.json is deprecated (https://zeit.ink/5F)
    now-project-id: # optional
    # Now CLI 17+, ❗️  The `name` property in now.json is deprecated (https://zeit.ink/5F)
    now-org-id: # optional
